import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRoom,dict} from './helpers.js';
import {PETS,petAbility,CARDS,BLOCKS,CARD_BOXES} from '../public/js/shared/catalog.js';
function game(pets={}){const r=createRoom({seed:29});for(const [seat,id]of ['alice','bob','carol'].entries()){const c=r.join(id,{pet:pets[id]||null,cards:Object.fromEntries(CARDS.map(c=>[c.id,3]))});r.send(c,{t:'sit',seat});}r.send(r.conns.alice,{t:'host',action:'start'});r.engine.pick(r.engine.match.options[0]);return r;}
function queue(r,id,card,target,request){r.clock.advance(1100);r.send(r.conns[id],{t:'queueCard',matchId:r.engine.match.matchId,cardId:card,targetId:target,requestId:request});return r.conns[id].last('cardQueueResult');}
function attack(r,id,card,target,request){if(r.engine.match.typerId===id)r.engine.startTurn(r.engine.nextAlive(id));assert.equal(queue(r,id,card,target,request).ok,true);r.engine.startTurn(id);return r.conns[id].last('cardResult');}
test('approved catalog uses nine cards, sixteen pets, normalized crate odds and Mystic name',()=>{assert.equal(CARDS.length,9);assert.equal(PETS.length,16);assert.equal(CARDS.find(c=>c.id==='arcane_ward').name,'Nope');for(const box of [...BLOCKS,...CARD_BOXES])assert.equal(Object.values(box.odds).reduce((a,b)=>a+b),100);assert.equal(BLOCKS[1].name,'Mystic Block');assert.equal(CARD_BOXES[1].odds.arcane_ward,3);assert.equal(CARD_BOXES[1].odds.mirrored_shield,2);assert.equal(petAbility('robot','roulette').value,.3);assert.equal(petAbility('owl','word_tide').value,.25);});
test('Nope arms on another player, cannot overwrite or disarm, consumes once and can rearm',()=>{const r=game(),m=r.engine.match,actor=r.engine.nextAlive(m.typerId),target=r.engine.nextAlive(actor),other=m.typerId;assert.equal(queue(r,actor,'arcane_ward',target,'arm').ok,true);assert.equal(r.engine.players.get(actor).cards.arcane_ward,2);assert.equal(queue(r,actor,'arcane_ward',target,'overwrite').reason,'already_armed');attack(r,other,'time_tax',target,'tax');assert.equal(r.engine.participant(target).pending.time,0);assert.equal(r.engine.participant(target).defense,null);assert.equal(r.conns[actor].last('cardDefense').reflected,false);r.clock.advance(5300);r.engine.startTurn(other);assert.equal(queue(r,actor,'arcane_ward',target,'rearm').ok,true);assert.deepEqual(r.errors,[]);});
test('Mirrored Shield reflects once without consuming a second already armed defense',()=>{const r=game(),m=r.engine.match,actor=r.engine.nextAlive(m.typerId),target=r.engine.nextAlive(actor),other=m.typerId;queue(r,actor,'mirrored_shield',target,'mirror');queue(r,actor,'arcane_ward',other,'protect-sender');attack(r,other,'time_tax',target,'tax');assert.equal(r.engine.participant(other).pending.time,2);assert.ok(r.engine.participant(other).defense);assert.equal(r.engine.participant(target).pending.time,0);assert.equal(r.conns[actor].last('cardDefense').reflected,true);});
test('unused armed cards return exactly once at natural end and reconnect',()=>{const r=game(),actor=r.engine.nextAlive(r.engine.match.typerId);queue(r,actor,'arcane_ward',actor,'unused');r.engine.endMatch(actor);assert.equal(r.engine.players.get(actor).cards.arcane_ward,3);const receipt=r.conns[actor].last('cardReturned');assert.ok(receipt);r.engine.endMatch(actor);assert.equal(r.engine.players.get(actor).cards.arcane_ward,3);const c=r.join(actor,{cards:{arcane_ward:0}});assert.equal(c.last('cardReturned').receipt,receipt.receipt);});
test('cancelling a match refunds armed copies once through normal card refunds',()=>{const r=game(),actor=r.engine.nextAlive(r.engine.match.typerId);queue(r,actor,'arcane_ward',actor,'arm');r.engine.cancelMatch();assert.equal(r.engine.players.get(actor).cards.arcane_ward,3);assert.deepEqual(r.conns[actor].last('matchRefund').cards,['arcane_ward']);r.engine.cancelMatch();assert.equal(r.engine.players.get(actor).cards.arcane_ward,3);});
test('Narrow Margin persists, Slow Burn stacks for two turns and respects six second floor',()=>{const r=game(),m=r.engine.match,actor=r.engine.nextAlive(m.typerId),target=r.engine.nextAlive(actor);attack(r,actor,'pressure',target,'margin');r.clock.advance(5300);r.engine.startTurn(target);assert.equal(m.maxMistakes,3);r.engine.startTurn(target);assert.equal(m.maxMistakes,3);const p=r.engine.participant(target);p.burns=Array(20).fill(2);r.engine.startTurn(target);assert.equal(m.duration,6000);assert.equal(p.burns.length,20);r.engine.startTurn(target);assert.equal(p.burns.length,0);r.engine.startTurn(target);assert.equal(m.duration,15000);});
test('Card Jam blocks new card queues and expires after target answers',()=>{const r=game(),m=r.engine.match,actor=r.engine.nextAlive(m.typerId),target=r.engine.nextAlive(actor);attack(r,actor,'card_jam',target,'jam');r.clock.advance(5300);r.engine.startTurn(actor);assert.equal(queue(r,target,'arcane_ward',target,'blocked').reason,'card_jammed');r.engine.startTurn(target);const word=dict.randomWithPrefix(m.prefix,m.used,()=>.2,{minLen:m.minLength,maxLen:8});r.send(r.conns[target],{t:'submit',word});assert.equal(r.engine.participant(target).jammed,false);});
test('Heartbreaker and Lifeline have meaningful 50 percent hit/miss behavior',()=>{for(const [random,hit]of [[.49,true],[.5,false]]){const r=game(),m=r.engine.match,actor=r.engine.nextAlive(m.typerId),target=r.engine.nextAlive(actor);r.engine.random=()=>random;attack(r,actor,'heart',target,'heart');r.clock.advance(4700);assert.equal(r.engine.participant(target).hearts,hit?1:2);}for(const [random,hearts]of [[.49,2],[.5,1]]){const r=game(),m=r.engine.match,actor=r.engine.nextAlive(m.typerId);r.engine.participant(actor).hearts=1;r.engine.random=()=>random;attack(r,actor,'lifeline',actor,'heal');assert.equal(r.engine.participant(actor).hearts,hearts);}});
test('counter pets stop Blaze once, enforce timer floor, soften taxes and block pressure once',()=>{for(const [pet,expected]of [['shellback',8000],['frostbite',13000],['badger',3000]]){const r=game({alice:pet});r.engine.startTurn('alice',2000,true);assert.equal(r.engine.match.duration,expected);if(pet==='frostbite'){r.engine.startTurn('alice',0,true);assert.equal(r.engine.match.duration,3000);}}const r=game({alice:'badger'});r.engine.participant('alice').pending.time=2;r.engine.startTurn('alice');assert.equal(r.engine.match.duration,14000);const q=game({alice:'moth'}),actor=q.engine.nextAlive(q.engine.match.typerId)==='alice'?'bob':q.engine.nextAlive(q.engine.match.typerId);q.engine.startTurn(q.engine.nextAlive(actor));attack(q,actor,'pressure','alice','pressure');assert.equal(q.engine.participant('alice').mistakePenalty||0,0);assert.equal(q.engine.participant('alice').mistakeGuardUsed,true);});
test('matched Last Sip stakes let either winner profit, refund excess, conserve coins and mint no trophies',()=>{for(const bets of [[5000,5000],[5000,25],[25,5000]])for(const winner of ['alice','bob']){const r=createRoom(),a=r.join('alice'),b=r.join('bob');for(const [i,c]of [a,b].entries()){const id=['alice','bob'][i];r.engine.players.get(id).accountCreatedAt=-1e8;r.send(c,{t:'sit',seat:i});}r.send(a,{t:'host',action:'settings',settings:{mode:'roulette'}});for(const [i,c]of [a,b].entries())r.send(c,{t:'bet',requestId:'bet-'+i,amount:bets[i],balance:10000});r.send(a,{t:'host',action:'start'});const m=r.engine.match,matched=Math.min(...bets);assert.equal(m.roulette.basePot,matched*2);m.roulette.pot=m.roulette.payoutCap;r.engine.endRoulette(winner);const rewards=[a,b].map(c=>c.last('rouletteReward'));assert.equal(rewards[0].coins+rewards[1].coins,bets[0]+bets[1]-Math.ceil(matched*2*.1));const i=winner==='alice'?0:1;assert.ok(rewards[i].coins>bets[i]);assert.equal(rewards[i].earnsTrophy,false);assert.equal(r.engine.players.get(winner).wins,0);assert.deepEqual(r.errors,[]);}});
test('a departing owner receives an unused defense refund on return to the room',()=>{const r=game(),m=r.engine.match,owner=r.engine.nextAlive(m.typerId),target=r.engine.nextAlive(owner),winner=m.typerId;queue(r,owner,'arcane_ward',target,'departed-arm');r.engine.removePlayer(owner);r.engine.endMatch(winner);assert.ok(r.engine.rouletteReceipts.get(owner).some(([,v])=>v.t==='cardReturned'));const c=r.join(owner,{cards:{arcane_ward:2}});assert.equal(c.last('cardReturned').cardId,'arcane_ward');});
test('retired Double Trouble cannot be selected through host settings',()=>{const r=createRoom(),a=r.join('alice');r.send(a,{t:'host',action:'settings',settings:{mode:'double'}});assert.equal(r.engine.settings.mode,'classic');assert.deepEqual(r.errors,[]);});
