// Generates the committed word lists from SCOWL (npm package `wordlist-english`):
//   src/words.js    — full dictionary used to validate submissions
//   src/botwords.js — common, short words that bots prefer
// Each module default-exports ONE string: sorted, unique, lowercase a-z words joined by '\n'.
// Usage: npm run build:words
import { readFileSync, writeFileSync } from 'node:fs';
import { MIN_WORD_LENGTH, MAX_WORD_LENGTH } from '../public/js/shared/constants.js';
import { isBlockedWord } from '../src/blocklist.js';

const SOURCE = new URL('../node_modules/wordlist-english/', import.meta.url);
const TIERS = [10, 20, 35, 40, 50, 55, 60, 70];

// A tier file lists only the words that are NEW at that tier, so a list is the union of tiers.
function collect({ variants, maxTier, minLength, maxLength }) {
  const words = new Set();
  const blocked = new Set();
  for (const variant of variants) {
    for (const tier of TIERS.filter((t) => t <= maxTier)) {
      const file = new URL(`${variant}-words-${tier}.json`, SOURCE);
      for (const word of JSON.parse(readFileSync(file, 'utf8'))) {
        // Skips proper nouns (uppercase), contractions (apostrophes) and accented words.
        if (!/^[a-z]+$/.test(word) || word.length < minLength || word.length > maxLength) continue;
        (isBlockedWord(word) ? blocked : words).add(word);
      }
    }
  }
  // Default JS string order, the same order the dictionary's binary search relies on.
  return { words: [...words].sort(), blocked: [...blocked].sort() };
}

function write(fileName, description, words) {
  const source =
    `// Generated by scripts/build-words.mjs — do not edit by hand.\n` +
    `// ${description}: ${words.length} words, sorted, one per line.\n` +
    `export default \`${words.join('\n')}\`;\n`;
  writeFileSync(new URL(`../src/${fileName}`, import.meta.url), source);
  console.log(`src/${fileName}: ${words.length} words, ${(source.length / 1024).toFixed(0)} KiB`);
}

const full = collect({
  variants: ['english', 'american', 'british', 'canadian'],
  maxTier: 70,
  minLength: MIN_WORD_LENGTH,
  maxLength: MAX_WORD_LENGTH,
});
const bots = collect({ variants: ['english', 'american'], maxTier: 35, minLength: MIN_WORD_LENGTH, maxLength: 9 });

const dictionary = new Set(full.words);
if (!bots.words.every((w) => dictionary.has(w))) throw new Error('bot words must be a subset of the dictionary');

write('words.js', 'Full dictionary (SCOWL english+american+british+canadian, sizes 10-70)', full.words);
write('botwords.js', 'Common words for bots (SCOWL english+american, sizes 10-35, 3-9 letters)', bots.words);
console.log(`blocklisted and removed: ${full.blocked.join(', ')}`);
