// Original curated bank, common English categories. Explicit spellings prevent adjective padding.
// Each pipe-separated form is accepted and earns its own alphabetic length (no alias inflation).
import { TIDE } from '../public/js/shared/word-tide.js';
export const normalizeTideAnswer = value => typeof value === 'string' && value.length <= 100 ? value.normalize('NFKC').toLowerCase().trim().replace(/[’']/g, '').replace(/[-\s]+/g, ' ') : '';
const rows = [
 ['fruit','Name a fruit',10,'apple|banana|orange|pineapple|watermelon|strawberry|raspberry|blackberry|blueberry|grapefruit|mango|papaya|coconut|passion fruit|dragon fruit|pomegranate|kiwi|pear|peach|apricot|plum|cherry|grape|guava|lychee|cantaloupe'],
 ['vegetable','Name a vegetable',9,'carrot|potato|sweet potato|broccoli|cauliflower|spinach|cabbage|red cabbage|lettuce|cucumber|bell pepper|onion|garlic|asparagus|eggplant|aubergine|zucchini|courgette|pumpkin|celery|beetroot|turnip|radish|brussels sprouts|artichoke'],
 ['ocean','Name an animal that lives in the ocean',10,'shark|dolphin|whale|blue whale|humpback whale|killer whale|orca|octopus|squid|giant squid|jellyfish|sea turtle|sea lion|sea otter|starfish|sea star|seahorse|clownfish|swordfish|hammerhead shark|great white shark|stingray|manta ray|lobster|crab|shrimp|seal|walrus'],
 ['mammal','Name a mammal',10,'cat|dog|elephant|giraffe|rhinoceros|hippopotamus|hippo|raccoon|squirrel|chimpanzee|orangutan|gorilla|kangaroo|platypus|armadillo|hedgehog|porcupine|dolphin|whale|bat|horse|tiger|lion|leopard|cheetah|polar bear|brown bear|giant panda|rabbit|hamster'],
 ['bird','Name a bird',9,'eagle|bald eagle|golden eagle|parrot|penguin|emperor penguin|flamingo|woodpecker|hummingbird|kingfisher|albatross|pelican|ostrich|emu|toucan|cockatoo|macaw|sparrow|pigeon|robin|crow|raven|owl|barn owl|snowy owl|chicken|turkey|duck|goose|swan'],
 ['insect','Name an insect',9,'ant|bee|honeybee|bumblebee|butterfly|dragonfly|grasshopper|ladybug|ladybird|mosquito|cockroach|beetle|stag beetle|dung beetle|firefly|termite|cricket|moth|praying mantis|stick insect|wasp|hornet|cicada|flea'],
 ['pet','Name an animal people keep as a pet',9,'dog|cat|goldfish|hamster|guinea pig|rabbit|parrot|budgerigar|budgie|cockatiel|cockatoo|gerbil|chinchilla|ferret|turtle|tortoise|snake|lizard|gecko|bearded dragon|canary|mouse|rat|hedgehog'],
 ['farm','Name an animal found on a farm',8,'cow|horse|chicken|pig|sheep|goat|donkey|turkey|duck|goose|rabbit|alpaca|llama|buffalo|water buffalo|ox|rooster|pony'],
 ['reptile','Name a reptile',10,'snake|lizard|turtle|tortoise|crocodile|alligator|chameleon|iguana|gecko|komodo dragon|bearded dragon|boa constrictor|rattlesnake|python|cobra|king cobra|anaconda|sea turtle'],
 ['coldanimal','Name an animal found in polar regions',10,'polar bear|arctic fox|arctic hare|arctic wolf|reindeer|caribou|musk ox|walrus|seal|elephant seal|leopard seal|penguin|emperor penguin|adelie penguin|snowy owl|beluga whale|narwhal|orca'],
 ['breakfast','Name a breakfast food',10,'toast|cereal|oatmeal|porridge|pancakes|waffles|scrambled eggs|fried eggs|boiled eggs|omelette|omelet|bacon|sausage|yogurt|yoghurt|granola|french toast|hash browns|bagel|croissant|breakfast burrito|fruit salad'],
 ['dessert','Name a dessert',11,'cake|ice cream|chocolate cake|cheesecake|apple pie|brownie|cookie|cookies|cupcake|pudding|tiramisu|creme brulee|banana split|chocolate mousse|rice pudding|carrot cake|lemon tart|sorbet|gelato|chocolate chip cookie|strawberry shortcake'],
 ['pizza','Name a pizza topping',9,'cheese|mozzarella|pepperoni|mushroom|mushrooms|bell pepper|bell peppers|onion|onions|olive|olives|black olives|sausage|pineapple|ham|bacon|chicken|anchovies|spinach|tomato|tomatoes|jalapeno|basil|artichoke'],
 ['sandwich','Name something you put in a sandwich',9,'bread|cheese|lettuce|tomato|tomatoes|ham|turkey|chicken|bacon|tuna|mayonnaise|mustard|peanut butter|jam|jelly|cucumber|avocado|egg|salami|roast beef|cream cheese'],
 ['drink','Name a nonalcoholic drink',10,'water|milk|orange juice|apple juice|pineapple juice|grape juice|lemonade|hot chocolate|chocolate milk|milkshake|strawberry milkshake|smoothie|tea|iced tea|coffee|coconut water|sparkling water|soda|cola|root beer|ginger ale'],
 ['pasta','Name a type of pasta',10,'spaghetti|macaroni|penne|fusilli|rigatoni|linguine|fettuccine|tagliatelle|tortellini|ravioli|lasagne|lasagna|farfalle|cannelloni|orzo|vermicelli|pappardelle|bucatini'],
 ['cheese','Name a type of cheese',10,'cheddar|mozzarella|parmesan|gouda|brie|camembert|feta|ricotta|provolone|gorgonzola|roquefort|mascarpone|cream cheese|cottage cheese|monterey jack|swiss cheese|edam|halloumi'],
 ['herb','Name a culinary herb or spice',9,'basil|oregano|thyme|rosemary|parsley|coriander|cilantro|cinnamon|nutmeg|turmeric|paprika|cumin|cardamom|black pepper|cayenne pepper|ginger|cloves|saffron|sage|dill|mint|tarragon'],
 ['baking','Name an ingredient used in baking',10,'flour|sugar|butter|eggs|milk|yeast|baking powder|baking soda|vanilla extract|chocolate chips|cocoa powder|brown sugar|powdered sugar|icing sugar|salt|cream|honey|cinnamon|vegetable oil|cornstarch'],
 ['icecream','Name an ice cream flavor',10,'vanilla|chocolate|strawberry|mint chocolate chip|cookies and cream|cookie dough|chocolate chip|rocky road|butter pecan|pistachio|coffee|mango|coconut|raspberry|salted caramel|neapolitan|bubblegum|banana'],
 ['sport','Name a sport',10,'football|soccer|basketball|baseball|volleyball|tennis|table tennis|badminton|cricket|rugby|swimming|synchronized swimming|synchronised swimming|gymnastics|skateboarding|snowboarding|ice hockey|field hockey|american football|water polo|handball|golf|boxing|fencing|archery|cycling'],
 ['wateractivity','Name a water sport',10,'swimming|surfing|windsurfing|kitesurfing|kayaking|canoeing|rowing|sailing|water polo|water skiing|wakeboarding|paddleboarding|stand up paddleboarding|diving|synchronized swimming|synchronised swimming|whitewater rafting|snorkeling|snorkelling|scuba diving'],
 ['instrument','Name a musical instrument',10,'piano|guitar|electric guitar|acoustic guitar|violin|viola|cello|double bass|trumpet|trombone|saxophone|clarinet|flute|piccolo|oboe|bassoon|harmonica|accordion|xylophone|glockenspiel|tambourine|ukulele|harp|drums|triangle|french horn'],
 ['school','Name a school subject',10,'math|maths|mathematics|english|science|biology|chemistry|physics|history|geography|art|music|physical education|computer science|drama|economics|social studies|spanish|french|literature|algebra|geometry'],
 ['classroom','Name something found in a classroom',10,'desk|chair|table|whiteboard|blackboard|chalkboard|pencil|pen|eraser|rubber|ruler|notebook|textbook|computer|projector|pencil sharpener|bulletin board|bookshelf|globe|scissors|calculator|marker|crayon'],
 ['bag','Name something in a school bag',10,'book|textbook|notebook|pencil|pen|pencil case|eraser|ruler|calculator|lunch box|lunchbox|water bottle|highlighter|colored pencils|coloured pencils|pencil sharpener|homework|folder|binder|scissors'],
 ['job','Name a job',10,'teacher|doctor|nurse|firefighter|police officer|engineer|software engineer|astronaut|scientist|veterinarian|dentist|electrician|carpenter|plumber|accountant|architect|chef|baker|farmer|pilot|flight attendant|photographer|journalist|librarian|mechanic'],
 ['transport','Name a form of transportation',10,'car|bus|train|bicycle|motorcycle|airplane|aeroplane|helicopter|boat|ship|ferry|submarine|hot air balloon|skateboard|scooter|tram|subway|truck|taxi|rickshaw|snowmobile|hovercraft'],
 ['road','Name a vehicle you might see on a road',10,'car|bus|truck|motorcycle|bicycle|scooter|ambulance|fire engine|fire truck|police car|garbage truck|rubbish truck|school bus|delivery van|camper van|limousine|tractor|taxi|pickup truck|cement mixer'],
 ['room','Name a room in a house',10,'bedroom|bathroom|living room|dining room|kitchen|laundry room|utility room|guest bedroom|master bedroom|study|office|home office|playroom|family room|attic|basement|pantry|nursery|conservatory'],
 ['kitchen','Name something found in a kitchen',11,'refrigerator|fridge|freezer|dishwasher|microwave|oven|stove|toaster|blender|food processor|electric kettle|kettle|coffee maker|cutting board|chopping board|frying pan|saucepan|spatula|colander|rolling pin|measuring cup|can opener|sink'],
 ['bathroom','Name something found in a bathroom',11,'toilet|sink|bathtub|shower|mirror|toothbrush|electric toothbrush|toothpaste|dental floss|towel|hand towel|shampoo|conditioner|soap|toilet paper|hairbrush|hair dryer|shower curtain|bath mat'],
 ['bedroom','Name something found in a bedroom',10,'bed|pillow|blanket|duvet|mattress|wardrobe|dresser|nightstand|bedside table|alarm clock|lamp|curtains|bookshelf|mirror|clothes|clothes hanger|chest of drawers|bunk bed|desk'],
 ['furniture','Name a piece of furniture',10,'chair|table|sofa|couch|armchair|bed|wardrobe|bookcase|bookshelf|desk|dresser|nightstand|bedside table|coffee table|dining table|rocking chair|chest of drawers|ottoman|stool|bench|cabinet'],
 ['clothing','Name an item of clothing',10,'shirt|t shirt|trousers|pants|jeans|shorts|dress|skirt|sweater|jumper|cardigan|sweatshirt|hoodie|jacket|coat|raincoat|windbreaker|swimsuit|bathing suit|socks|underwear|pajamas|pyjamas|overalls|leggings'],
 ['headwear','Name something you wear on your head',9,'hat|cap|baseball cap|beanie|helmet|bicycle helmet|hard hat|crown|tiara|headband|bandana|beret|fedora|sombrero|sun hat|cowboy hat|top hat|party hat|headphones|earmuffs'],
 ['footwear','Name a type of footwear',10,'shoes|boots|sandals|slippers|sneakers|trainers|running shoes|hiking boots|rain boots|wellington boots|flip flops|high heels|ballet slippers|loafers|moccasins|snow boots|football boots|roller skates|ice skates'],
 ['camping','Name something you take camping',11,'tent|sleeping bag|flashlight|torch|lantern|backpack|water bottle|camping stove|first aid kit|insect repellent|sunscreen|compass|map|matches|food|rope|hiking boots|raincoat|sleeping pad|pocket knife'],
 ['beach','Name something you take to the beach',10,'towel|beach towel|sunscreen|sunglasses|sun hat|umbrella|beach umbrella|swimsuit|bathing suit|flip flops|sandals|bucket|shovel|beach ball|surfboard|water bottle|snorkel|picnic basket|cooler|inflatable ring'],
 ['garden','Name something found in a garden',10,'flower|flowers|tree|bush|grass|soil|fence|watering can|garden hose|lawn mower|wheelbarrow|flower pot|bird feeder|birdbath|garden gnome|compost bin|greenhouse|rake|shovel|butterfly|earthworm'],
 ['tool','Name a hand tool',10,'hammer|screwdriver|wrench|spanner|pliers|handsaw|saw|chisel|file|tape measure|spirit level|allen key|hex key|adjustable wrench|socket wrench|wire cutters|utility knife|clamp|crowbar'],
 ['technology','Name an electronic device',10,'computer|laptop|tablet|smartphone|mobile phone|television|radio|calculator|camera|digital camera|headphones|printer|scanner|projector|smartwatch|game console|microwave|router|e reader'],
 ['computer','Name a computer part or accessory',10,'keyboard|mouse|monitor|processor|motherboard|graphics card|hard drive|solid state drive|power supply|memory|ram|webcam|microphone|speakers|headphones|printer|scanner|usb drive|touchpad'],
 ['shape','Name a geometric shape',10,'circle|triangle|square|rectangle|pentagon|hexagon|heptagon|octagon|nonagon|decagon|oval|ellipse|rhombus|trapezoid|trapezium|parallelogram|semicircle|cube|sphere|cylinder|cone|pyramid'],
 ['color','Name a color',9,'red|orange|yellow|green|blue|purple|pink|brown|black|white|gray|grey|turquoise|aquamarine|magenta|maroon|lavender|indigo|violet|chartreuse|crimson|scarlet|coral|teal|navy blue|royal blue|forest green'],
 ['weather','Name a weather phenomenon',10,'rain|snow|hail|sleet|fog|mist|wind|thunder|lightning|thunderstorm|hurricane|tornado|blizzard|rainbow|heat wave|sandstorm|dust storm|freezing rain|drizzle|waterspout'],
 ['landform','Name a natural landform',10,'mountain|hill|valley|plateau|canyon|cliff|peninsula|island|archipelago|volcano|glacier|sand dune|delta|plain|waterfall|cave|beach|desert|ravine|gorge'],
 ['tree','Name a type of tree',10,'oak|pine|maple|birch|willow|weeping willow|palm|coconut palm|redwood|sequoia|eucalyptus|acacia|baobab|cherry|apple|mango|cedar|cypress|sycamore|mahogany|chestnut'],
 ['flower','Name a flower',10,'rose|tulip|daisy|sunflower|daffodil|dandelion|chrysanthemum|orchid|lily|lavender|hibiscus|marigold|carnation|geranium|hydrangea|bluebell|poppy|peony|lotus|water lily|snapdragon'],
 ['country','Name a country',11,'canada|mexico|united states|united states of america|brazil|argentina|chile|peru|colombia|united kingdom|france|germany|spain|portugal|italy|greece|netherlands|switzerland|sweden|norway|denmark|finland|iceland|ireland|poland|ukraine|australia|new zealand|japan|china|india|indonesia|thailand|philippines|singapore|malaysia|south korea|south africa|egypt|kenya|nigeria|madagascar|saudi arabia|united arab emirates'],
 ['europe','Name a country in Europe',10,'france|germany|spain|portugal|italy|greece|netherlands|belgium|luxembourg|switzerland|austria|sweden|norway|denmark|finland|iceland|ireland|united kingdom|poland|czechia|czech republic|slovakia|slovenia|croatia|serbia|romania|bulgaria|albania|ukraine|estonia|latvia|lithuania|hungary|malta|andorra|monaco|san marino|liechtenstein|bosnia and herzegovina|north macedonia|montenegro|moldova|belarus'],
 ['africa','Name a country in Africa',10,'egypt|kenya|nigeria|ghana|south africa|morocco|algeria|tunisia|libya|sudan|south sudan|ethiopia|somalia|tanzania|uganda|rwanda|zambia|zimbabwe|botswana|namibia|madagascar|mozambique|cameroon|senegal|angola|ivory coast|central african republic|democratic republic of the congo|republic of the congo|sierra leone|burkina faso|equatorial guinea'],
 ['asia','Name a country in Asia',10,'china|japan|india|pakistan|bangladesh|nepal|bhutan|sri lanka|maldives|thailand|vietnam|cambodia|laos|myanmar|malaysia|singapore|indonesia|philippines|mongolia|south korea|north korea|saudi arabia|united arab emirates|qatar|bahrain|kuwait|oman|yemen|jordan|lebanon|iraq|iran|afghanistan|kazakhstan|uzbekistan|kyrgyzstan|tajikistan|turkmenistan'],
 ['state','Name a US state',11,'alabama|alaska|arizona|arkansas|california|colorado|connecticut|delaware|florida|georgia|hawaii|idaho|illinois|indiana|iowa|kansas|kentucky|louisiana|maine|maryland|massachusetts|michigan|minnesota|mississippi|missouri|montana|nebraska|nevada|new hampshire|new jersey|new mexico|new york|north carolina|north dakota|ohio|oklahoma|oregon|pennsylvania|rhode island|south carolina|south dakota|tennessee|texas|utah|vermont|virginia|washington|west virginia|wisconsin|wyoming'],
 ['body','Name a part of the human body',9,'head|arm|leg|hand|foot|finger|toe|shoulder|elbow|wrist|knee|ankle|neck|back|chest|stomach|forehead|eyebrow|eyelash|eye|ear|nose|mouth|tongue|tooth|teeth|fingernail|collarbone|shoulder blade|belly button'],
 ['space','Name something found in space',10,'star|planet|moon|asteroid|comet|meteor|meteorite|galaxy|nebula|black hole|neutron star|white dwarf|red giant|supernova|space station|satellite|spacecraft|dwarf planet|asteroid belt'],
 ['metal','Name a metal',9,'iron|gold|silver|copper|aluminum|aluminium|titanium|platinum|nickel|zinc|tin|lead|mercury|magnesium|tungsten|chromium|cobalt|palladium|sodium|potassium'],
 ['dinosaur','Name a dinosaur',12,'tyrannosaurus|tyrannosaurus rex|triceratops|stegosaurus|brachiosaurus|diplodocus|velociraptor|ankylosaurus|spinosaurus|allosaurus|iguanodon|parasaurolophus|pachycephalosaurus|carnotaurus|apatosaurus|compsognathus'],
 ['playground','Name something found in a playground',10,'slide|swing|swings|swing set|seesaw|sandpit|sandbox|climbing frame|monkey bars|roundabout|merry go round|jungle gym|spring rider|balance beam|bench|basketball hoop|hopscotch'],
 ['holiday','Name a holiday or celebration',10,'christmas|halloween|easter|thanksgiving|new years day|new years eve|valentines day|independence day|labor day|labour day|memorial day|veterans day|mothers day|fathers day|saint patricks day|st patricks day|lunar new year|diwali|hanukkah|eid al fitr|eid al adha'],
];
export const TIDE_BANK = rows.map(([id, prompt, referenceLength, words]) => ({ id, prompt, referenceLength, answers: words.split('|') }));
const lookup = new Map(TIDE_BANK.map(c => [c.id, new Map(c.answers.map(word => [normalizeTideAnswer(word), word]))]));
export function validateTideAnswer(categoryId, value) {
 const key = normalizeTideAnswer(value), word = lookup.get(categoryId)?.get(key);
 if (!word) return null;
 const letters = word.replace(/[^a-z]/g, '').toUpperCase();
 return letters.length <= TIDE.maxLetters ? { word, letters, length: letters.length } : null;
}
